version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  api:
    container_name: app-api
    build:
      context: ./app
      target: production
    image: docker/node-web-app
    depends_on:
      - db
    ports:
      - 4200:3000
    environment:
      NODE_ENV: production
      IMMO_DB_HOST: db
      DB_PORT: 5432
      IMMO_DB_USER: postgres
      IMMO_DB_PASSWORD: postgres
      IMMO_DB: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local